name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-plz

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_CONFIG_FUND: false

concurrency:
  group: release-plz

jobs:
  release-plz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jdx/mise-action@v2
      - run: mise run release-plz
        env:
          DRY_RUN: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
